### ISSUE TITLE
Expose port for dashboard agent (needed for serve deploy)

### ISSUE THREAD

**Issue by ghpu** [richardsliu/ray-on-gke#9]
First of all, thanks for this very usefull deployment template, very much appreciated !

I wanted to use ray serve, but the dashboard agent port (52365) was not exposed by the current service in Kuberay operator (v0.5.0) .

Easy work-around : add
```
head:
  ports:
        - containerPort: 6379
          name: gcs-server
        - containerPort: 8265 # Ray dashboard
          name: dashboard
        - containerPort: 10001
          name: client
        - containerPort: 52365
          name: dashboard-agent
```

to kuberay-values.yaml
